version: '3.8'

services:
  mysql: 
     image: mysql:8.0
     container_name: mysql
     ports:
      - "3307:3306"
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: access_control_db
       MYSQL_USER: user
       MYSQL_PASSWORD: password
     networks:
     - app-network
     volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: src/Dockerfile  # Renamed for clarity
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/access_control_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    networks:
      - app-network

  frontend:
    build:
      context: ./assets/access-control-system
      dockerfile: Dockerfile  
    ports:
      - "8080:8080" 
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
